### ISSUE TITLE
Virtual env?

### ISSUE THREAD

**Issue by akohli96** [RadioactiveRadium/DjangoBlog#1]
Bro did you create a virtual env or global django install?

I am going through the tutorial as well.

Try djangogirls tutorial too

**Comment by AlecWaichunas** [comment]
Did you install Django? It installed really easily through pip for me.
After that I just used "py -m django startproject mysite" and my workspace was generated
Then to run the server locally it was "py manage.py runserver"

I'm slowly drifting from the tutorial now, but I just went through this pretty fast https://docs.djangoproject.com/en/1.10/intro/tutorial01/

**Comment by akohli96** [comment]
I first created a virtual env and then installed Django and am going through the tutorial. 
Go to it-ebooks or something. There are a hell of a lot of Django resources.

Imma look into google maps python api and twillio.

**Comment by AlecWaichunas** [comment]
I'll look into that. I'm just going to get a database up and going and mess around with it for a bit. Try and find the easiest ways to set up and interact the client with the server. I'll probably venture off later this week and get an understanding of those APIs.

**Comment by akohli96** [comment]
Postgres is very popular since it has a json type too. Tbh, sqlite works as well which is default database django offers. 

Also see if there is some boilerplate that offers register with etc
